// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-kpi-cards/AsymmetricHero.tsx": () => import("../components/mockups/hero-kpi-cards/AsymmetricHero.tsx"),
  "./components/mockups/hero-kpi-cards/CompactFourCol.tsx": () => import("../components/mockups/hero-kpi-cards/CompactFourCol.tsx"),
  "./components/mockups/hero-kpi-cards/GlassDark.tsx": () => import("../components/mockups/hero-kpi-cards/GlassDark.tsx"),
  "./components/mockups/hero-kpi-cards/GradientBold.tsx": () => import("../components/mockups/hero-kpi-cards/GradientBold.tsx"),
  "./components/mockups/hero-kpi-cards/HorizontalStrip.tsx": () => import("../components/mockups/hero-kpi-cards/HorizontalStrip.tsx"),
  "./components/mockups/hero-kpi-cards/MinimalPremium.tsx": () => import("../components/mockups/hero-kpi-cards/MinimalPremium.tsx")
};
